version: '3.11'

services:
  db:
    image: postgres:15
    container_name: lab-db
    restart: always
    ports:
      - '5555:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: