version: '3.11'

services:
  db:
    image: postgres:15
    container_name: lab-pg-db
    restart: always
    ports:
      - '5555:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: lab-mongo-db
    restart: always
    ports:
      - '27717:27017'
    env_file:
      - .env
    environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  postgres_data: